[package]
name = "vhdx-cli"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
description = "CLI tool for inspecting VHDX disk images"
license.workspace = true
repository.workspace = true
keywords = ["forensics", "vhdx", "disk-image"]
categories = ["command-line-utilities"]
exclude = ["tests/"]

[[bin]]
name = "vhdx"
path = "src/main.rs"

[dependencies]
vhdx = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
